version: "3"
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
    restart: unless-stopped

  web:
    build:
      context: "."
    ports:
      - "8080:8080"
    environment:
      BIND_ADDRESS: 0.0.0.0:8080
      DATABASE_URL: postgres://postgres:secret@db:5432/postgres
    restart: unless-stopped
